/** Common English words, monkeytype-style. Neutral stream and attack words both draw from here. */
export const WORDS: string[] = [
  "the", "and", "for", "are", "but", "not", "you", "all", "can", "her",
  "was", "one", "our", "out", "day", "get", "has", "him", "his", "how",
  "man", "new", "now", "old", "see", "two", "way", "who", "boy", "did",
  "its", "let", "put", "say", "she", "too", "use", "that", "with", "have",
  "this", "will", "your", "from", "they", "know", "want", "been", "good",
  "much", "some", "time", "very", "when", "come", "here", "just", "like",
  "long", "make", "many", "more", "only", "over", "such", "take", "than",
  "them", "well", "were", "what", "work", "year", "back", "call", "came",
  "each", "even", "find", "give", "hand", "high", "keep", "last", "left",
  "life", "live", "look", "made", "most", "move", "must", "name", "need",
  "next", "open", "part", "play", "said", "same", "seem", "show", "side",
  "tell", "turn", "used", "want", "ways", "week", "went", "word", "world",
  "about", "after", "again", "below", "could", "every", "first", "found",
  "great", "house", "large", "learn", "never", "other", "place", "plant",
  "point", "right", "small", "sound", "spell", "still", "study", "their",
  "there", "these", "thing", "think", "three", "water", "where", "which",
  "write", "would", "little", "people", "before", "should", "because",
  "between", "through", "different", "another", "thought", "against",
  "number", "always", "follow", "around", "answer", "letter", "mother",
  "father", "friend", "school", "second", "enough", "almost", "change",
  "animal", "listen", "simple", "toward", "moment", "happen", "middle",
  "strong", "system", "moving", "better", "across", "during", "himself",
  "example", "picture", "country", "sentence", "mountain", "children",
  "important", "together", "question", "complete", "remember", "possible",
  "morning", "evening", "nothing", "problem", "however", "machine",
  "special", "believe", "measure", "product", "numeral", "certain",
  "correct", "science", "brought", "distant", "surface", "produce",
  "quickly", "person", "become", "family", "leave", "paper", "music",
  "color", "stand", "sun", "walk", "rain", "eye", "fire", "north",
  "piece", "told", "usually", "money", "story", "young", "fact",
  "months", "being", "study", "book", "carry", "took", "rain", "eat",
  "room", "idea", "fish", "grow", "state", "once", "hear", "stop",
  "without", "late", "miss", "brought", "heat", "snow", "bring", "yes",
  "distant", "fill", "east", "paint", "language", "among", "unit",
  "power", "town", "fine", "fall", "lead", "cry", "dark", "note",
  "wait", "plan", "figure", "star", "box", "noun", "field", "rest",
  "able", "pound", "done", "beauty", "drive", "stood", "contain",
  "front", "teach", "final", "gave", "green", "quick", "develop",
  "ocean", "warm", "free", "minute", "special", "strange", "behind",
  "clear", "tail", "space", "heard", "best", "hour", "true", "hundred",
  "five", "since", "against", "pattern", "slow", "center", "love",
];
